config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
	root 'pages#home'
	get "about", to: "pages#about"
	
  resources :articles

	get 'signup', to: 'users#new'
	post 'users', to: 'users#create'

	resources :users, except: [:new]

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
	resources :categories, except: [:destroy]  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
	validates :title, presence: true, length: {minimum: 6, maximum: 100}
	validates :description, presence: true, length: {minimum: 6, maximum: 100}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, length: {minimum: 3, maximum: 25}
	validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :articles, dependent: :destroy # if user is deleted then any associated dependents in our case, articles will be destroy
	validates :username, presence: true, 
											uniqueness: {case_sensitive: false},
											length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true,
										uniqueness: {case_sensitive: false}, 
										length: {maximum: 105},
										format: {with: VALID_EMAIL_REGEX}
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?
	def current_user 
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user 
		if !logged_in?
			flash[:alert] = "You must be logged in to perform that action"
			redirect_to login_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @article = Article.find(params[:id])
  end
  def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

  def new
    @article = Article.new
  end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash.now[:notice] = "Article was created successfully."
			redirect_to @article 
		else
			render "new"
		end
	end

  def edit
		
  end

	def update 
		if @article.update(article_params)
			flash.now[:notice] = "Article was updated succesfully"
			redirect_to @article
		else 
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path, status: :see_other
	end
	
	private 

	def set_article 
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, category_ids: [])
	end

	def require_same_user
		if current_user != @article.user && !current_user.admin?
			flash[:alert] = "You can only edit or delete your own article"
			redirect_to @article
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action  :require_admin, except: [:index, :show]
  def new
		@category = Category.new
  end
	def create 
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category was successfully created"
			redirect_to @category
		else
			render 'new'
		end
	end
  def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
		@category = Category.find(params[:id])
		@articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
		flash[:notice] = "Category name updated successfully"
		redirect_to @category
		else
			render 'edit'
		end
	end

	private
	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !(logged_in? && current_user.admin?)
			flash[:alert] = "Only admins can perform that action"
			redirect_to categories_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		# redirect_to articles_path
	end
	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = "Logged in successfully"
			redirect_to user
		else
			flash.now[:notice] = "There was something wrong with your login detail session"
			render 'now'
		end
	end
	def destroy 
		session[:user_id] = nil
		flash[:notice] = "Logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :require_user, only: [:edit, :update]
	before_action :require_same_user, only: [:edit, :update, :destroy]
  def show
		@articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def index
    @users = User.paginate(page: params[:page], per_page: 5)
	end

  def new
    @user = User.new
  end
  def edit
  end
  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  def create
    @user = User.new(user_params)
    if @user.save
			session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

	def destroy 
		@user.destroy
		session[:user_id] = nil if @user == current_user
		flash[:notice] = "Account and all associated articles successfully deleted"
		redirect_to articles_path
	end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
	def set_user
    @user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user && !current_user.admin?  # only logout when admin delete themself
			flash[:alert] = "You can only edit or delete your own account"
			redirect_to @user
		end

	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container m-auto">
	<% if @articles.any? %>
		<% @articles.each do |article| %>
			<div class="flex justify-center">
				<div class="block rounded-lg mb-5 shadow-lg bg-slate-100 max-w-xl text-center w-1/2 border-t-4">
					<div class="text-lg font-bold py-3 px-6 border-b border-gray-300 bg-slate-200">
						<% if article.user %>
							by <%= link_to article.user.username, user_path(article.user), class: "text-yellow-600" %>
						<% end %>
						<% if article.categories.any? %>
							<div class="mt-2">
								<%= render article.categories %>
							</div>
						<% end %>
					</div>
					<div class="p-6">
							<h5 class="text-2xl text-blue-500 font-bold card-title mt-2 mb-4"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
							<p class="card-text text-lg text-gray-400 mb-4"><%= truncate(article.description, length: 100) %></p>
							<%= link_to "View", article_path(article), class: "inline-block px-6 py-2.5 bg-blue-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out hover:text-blue-600" %>
							<% if logged_in? && (article.user == current_user  || current_user.admin?)%>
								<%= link_to "Edit", edit_article_path(article), class: " inline-block px-6 py-2.5 bg-yellow-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out hover:text-yellow-600" %>
								<%= link_to "Delete", article_path(article), class: "inline-block px-6 py-2.5 bg-red-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out hover:text-red-600", method: :delete, data: {"turbo-method": :delete, confirm: "Are you sure?"} %>
							<% end %>
					</div>
					<div class="py-3 px-6 border-t border-gray-300 text-gray-500">
							Created <%= time_ago_in_words(article.created_at) %> ago, 
							edited <%= time_ago_in_words(article.updated_at) %> ago
					</div>
				</div>
			</div>
  	<% end %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-20 text-blue-600 font-extrabold text-4xl mb-20"><%= @article.title %></h2>

  <div class="container m-auto">
			<div class="flex justify-center">
				<div class="block rounded-lg mb-5 shadow-lg bg-slate-100 max-w-xl text-center w-1/2 border-t-4">
					<div class="text-lg text-blue-400 font-bold py-3 px-6 border-b border-gray-300 bg-slate-200">
						<div class="mb-4">
							by <%= @article.user.username if @article.user%>
						</div>
						<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
						<% if @article.categories.any? %>
								<div class="mt-2">
									<%= render @article.categories %>
								</div>
						<% end %>
					</div>
            <div class="card-text text-left pt-10 pb-10" style="padding-left: 32px"><%= simple_format(@article.description) %></div>
						<div class="mb-4">						
							<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
								<%= link_to "Edit", edit_article_path(@article), class: "inline-block px-6 py-2.5 bg-yellow-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out hover:text-yellow-600" %>
								<%= link_to "Delete", article_path(@article), class: "inline-block px-6 py-2.5 bg-red-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out hover:text-red-600", method: :delete, data: {confirm: "Are you sure?"} %>
							<% end %>
						</div>
					<div class="py-3 px-6 border-t border-gray-300 text-gray-500">
							Created <%= time_ago_in_words(@article.created_at) %> ago, 
							edited <%= time_ago_in_words(@article.updated_at) %> ago
					</div>
				</div>
			</div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container pt-10 pb-10 m-auto w-1/2 border-4 border-indigo-200 border-y-indigo-500">
	<div class="row">
		<%= render 'shared/errors', obj: @category %>
			<%= render 'form' %>
			<div class="return-link">
				<%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
			</div>
	</div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-10 mb-20 font-extrabold text-blue-600 text-3xl">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container m-auto">
  <% @categories.each do |category| %>
		<div class="flex justify-center">
			<div class="block rounded-lg mb-5 shadow-lg bg-slate-100 max-w-xl text-center w-1/2 border-t-4">
				<div class="text-lg font-bold py-3 px-6 border-b border-gray-300 bg-slate-200">
					<%= link_to category.name, category_path(category), class: "text-yellow-600" %>
				</div>
	<div class="py-3 px-6 border-t border-gray-300 text-gray-500">
			Created <%= time_ago_in_words(category.created_at) %> ago, 
			edited <%= time_ago_in_words(category.updated_at) %> ago
	</div>
</div>
</div>
<% end %>
</div>>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/layouts/_navigation.html.erb
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<div class="shadow-md w-full text-gray-700 bg-slate-100 dark-mode:text-gray-200 dark-mode:bg-gray-800">
  <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
    <div class="p-4 flex flex-row items-center justify-between ">
				<%= link_to "ALPHA BLOG", root_path, class: "font-bold text-transparent text-4xl bg-clip-text bg-gradient-to-r from-purple-400 to-blue-600", id: "logo" %>
      <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
      <%= link_to "BLOGGERS", users_path, class: "text-blue-500 px-4 py-2 mt-2 text-lg font-semibold text-gray-900 bg-gray-200 rounded-lg dark-mode:bg-gray-700 dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>



			<div @click.away="open = false" class="relative" x-data="{ open: false }">
				<button @click="open = !open" class="flex flex-row items-center w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:focus:bg-gray-600 dark-mode:hover:bg-gray-600 md:w-auto md:inline md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
				<span class="text-lg text-blue-500">ARTICLES</span>
				<svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
				</button>
				<div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
					<div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800 absolute z-40">
					<% if logged_in? %>
						<%= link_to "Create new article", new_article_path, class: "block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
					<% end %>
						<%= link_to "View articles", articles_path, class: "block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
					</div>
				</div>
      </div> 

			<div @click.away="open = false" class="relative" x-data="{ open: false }">
			<button @click="open = !open" class="flex flex-row items-center w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:focus:bg-gray-600 dark-mode:hover:bg-gray-600 md:w-auto md:inline md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
			<span class="text-lg text-blue-500">CATEGORIES</span>
			<svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
			</button>
			<div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
				<div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
				<% if logged_in? && current_user.admin?%>
					<%= link_to "Create new category", new_category_path, class: "block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
				<% end %>
					<%= link_to "View categories", categories_path, class: "block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
				</div>
			</div>
			</div> 

      <% if logged_in? %>
      <div @click.away="open = false" class="relative" x-data="{ open: false }">
				<button @click="open = !open" class="flex flex-row items-center w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:focus:bg-gray-600 dark-mode:hover:bg-gray-600 md:w-auto md:inline md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
				<span class="text-lg text-blue-500"><%= "(Admin)" if current_user.admin? %> PROFILE</span>
				<svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
				</button>
				<div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
					<div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
						<%= link_to "View your profile", user_path(current_user), class: "block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
						<%= link_to "Edit your profile", edit_user_path(current_user), class: "block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
						<%= link_to "Delete profile", user_path(current_user), class: "block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline",  data: {"turbo-method": :delete, confirm: "Are you sure ? "} %>
					</div>
				</div>
      </div>  
			<%= link_to 'LOGOUT', logout_path, class: "text-blue-500 px-4 py-2 mt-2 text-lg font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline", method: :delete %>
			<% else %>
			<%= link_to 'LOG IN', login_path, class: "text-blue-500 px-4 py-2 mt-2 text-lg font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
      <%= link_to 'SIGN UP', signup_path, class: "text-blue-500 px-4 py-2 mt-2 text-lg font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
			<% end %>
    </nav>
		<div class="relative mx-auto text-gray-600 lg:block hidden">
      <input class="border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none"
        			type="search" name="search" placeholder="Search">
      <button type="submit" class="absolute right-0 top-0 mt-3 mr-2">
      <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                         version="1.1" id="Capa_1" x="0px" y="0px"
                         viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;"
                         xml:space="preserve"
                         width="512px" height="512px">
      <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
      </svg>
      </button>
    </div>
  </div>
</div>